"""Create documents model

Revision ID: 705bd78468dc
Revises: c3b9c4effd71
Create Date: 2026-09-30 00:20:40.074208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705bd78468dc'
down_revision: Union[str, Sequence[str], None] = 'c3b9c4effd71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('upload_status', sa.Enum('PENDING', 'UPLOADED', 'FAILED', name='documentuploadstatus'), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='documentprocessingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("document_type <> ''", name='ck_document_type_not_empty'),
    sa.CheckConstraint("filename <> ''", name='ck_document_filename_not_empty'),
    sa.CheckConstraint('page_count >= 0', name='ck_document_page_count_positive'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_document_size_bytes_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.execute(sa.text("DROP TYPE documentuploadstatus"))
    op.execute(sa.text("DROP TYPE documentprocessingstatus"))
    # ### end Alembic commands ###
