"""Improving documents table

Revision ID: e43b94172a6b
Revises: 705bd78468dc
Create Date: 2026-10-01 00:23:43.051290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e43b94172a6b'
down_revision: Union[str, Sequence[str], None] = '705bd78468dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
